blueprint:
  name: 📦Громкость колонки когда говорит и слушает
  domain: automation
  description: Громкость колонки когда говорит и слушает
  input:
    kolonka:
      name: Колонка
      description: Колонка
      selector:
        entity:
          domain: media_player
          integration: yandex_station
    level_voice_entity:
      name: Объект для громкости
      description: Объект для громкости
      selector:
        entity:
          domain: input_number
    no_trigger1:
      name: Исключение
      description: Игнорирование управление громкостью
      selector:
        entity:

max_exceeded: silent

variables:
  kolonka: !input kolonka
  kolonka_area: "{{kolonka.split('.')[1].split('_')[2]}}"
  level_voice_entity: !input level_voice_entity
  level_voice: "{{states(level_voice_entity)|float(0)}}"
  input_number_entity: "input_number.{{kolonka.split('.')[1].split('_')[2]}}_gromkost_kolonki"

  sensor_speak: "sensor.alice_{{kolonka_area}}_state_voice"
  sensor_volume: "yandex_station_{{kolonka_area}}_volume_level"
  input_entity_play_pause: "input_boolean.kolonka_{{kolonka_area}}_pauza_plei"

  old_level_voice: >-
    {%if state_attr(kolonka, 'volume_level')|float(0) >= states('input_number.gromkost_kolonki_kogda_govorit')|float(0)%}
    {{states('input_number.minimalnaia_gromkost_kolonki')|float(0)}}
    {%else%}
    {{state_attr(kolonka, 'volume_level')}}
    {%endif%}

trigger:
  - platform: state
    entity_id: !input kolonka
    attribute: alice_state
    to: LISTENING
  - platform: state
    entity_id: !input kolonka
    attribute: alice_state
    to: SPEAKING
condition:

  # - condition: template
  #   value_template: "{{state_attr(kolonka, 'volume_level')|float(0) != states(level_voice_entity)|float(0)}}"

  - condition: template
    value_template: "{{state_attr(kolonka, 'volume_level')|float(0) != states(level_voice_entity)|float(0) 
      or (state_attr(kolonka, 'volume_level')|float(0) == states(level_voice_entity)|float(0) 
          and as_timestamp(now()) - as_timestamp(states.sensor[sensor_volume].last_changed)|float(0) > 10 * 60)}}"

  - condition: template
    value_template: "{{state_attr(kolonka, 'is_volume_muted') == false}}"

  - condition: not
    conditions:
      - condition: state
        entity_id: !input no_trigger1
        state: 'on'


  - condition: not
    conditions:
      - condition: state
        entity_id: !input kolonka
        attribute: alice_state
        state: IDLE

action:



  # - condition: template
  #   value_template: "{{state_attr(kolonka, 'volume_level')|float(0) != states(level_voice_entity)|float(0)}}"
  - condition: template
    value_template: "{{state_attr(kolonka, 'volume_level')|float(0) != states(level_voice_entity)|float(0) 
      or (state_attr(kolonka, 'volume_level')|float(0) == states(level_voice_entity)|float(0) 
          and as_timestamp(now()) - as_timestamp(states.sensor[sensor_volume].last_changed)|float(0) > 10 * 60)}}"

  - condition: template
    value_template: "{{state_attr(kolonka, 'is_volume_muted') == false}}"

  - condition: not
    conditions:
      - condition: state
        entity_id: !input no_trigger1
        state: 'on'


  - condition: not
    conditions:
      - condition: state
        entity_id: !input kolonka
        attribute: alice_state
        state: IDLE





  - service: input_boolean.turn_on
    data: {}
    target:
      entity_id: '{{input_entity_play_pause}}'

  - service: media_player.volume_set
    target:
      entity_id: !input kolonka
    data:
      volume_level: "{{level_voice}}"

  - wait_for_trigger:
      - platform: state
        entity_id: !input kolonka
        attribute: alice_state
        to: IDLE
        for:
          hours: 0
          minutes: 0
          seconds: 2
    timeout: '00:10:00'

  - service: media_player.volume_set
    target:
      entity_id: !input kolonka
    data:
      volume_level: '{{old_level_voice}}'


  - service: input_boolean.turn_off
    data: {}
    target:
      entity_id: '{{input_entity_play_pause}}'


      # volume_level: >-
      #   {{ old_level_voice + (state_attr(kolonka, 'volume_level') - level_voice)|round(1,default=20) }}


      #   {%-if state_attr(kolonka, 'volume_level') != level_voice -%}
      #     {{- (old_level_voice + state_attr('media_player.zal_android_tv', 'volume_level') - level_voice)|round(1,default=20) -}}
      #   {%-else-%}
      #     {{-old_level_voice-}}
      #   {%-endif-%}  

  # - delay:
  #     hours: 0
  #     minutes: 0
  #     seconds: 1
  #     milliseconds: 0
# mode: single
mode: queued
max: 4