blueprint:
  name: 📢Громкость и пауза Ястанции когда говорит и слушает Алиса
  domain: automation
  description: |
    Зпускается при смене атрибута станции alice_state на LISTENING или при условии ниже на SPEAKING.
  input:
    in_station:
      name: Колонка
      description: Колонка
      selector:
        entity:
          domain: media_player
          integration: yandex_station
    in_level_voice_entity:
      name: Уровень громкости
      description: Уровень громкости когда говорит или слушает
      default: 0.5
      selector:
        number:
          min: 0
          max: 1
          step: 0.05
    in_speaking_condition:
      name: Запускать при событии SPEAKING
      description: Запускать при событии SPEAKING.
      default: false
      selector:
        boolean:
    in_pause_play:
      name: Дополнительно ставить на паузу
      description: Дополнительно ставить на паузу
      default: false
      selector:
        boolean:
    in_condition:
      name: (Доп) Условия для запуска
      description: Условия для запуска.
      default: []
      selector:
        action:

trace:
  stored_traces: 100

mode: parallel

max: 100

variables:
  in_station: !input in_station
  in_level_voice_entity: !input in_level_voice_entity
  in_pause_play: !input in_pause_play
  in_speaking_condition: !input in_speaking_condition
  level_voice: "{{in_level_voice_entity|float(0.5)}}"
  old_level_voice: "{{state_attr(in_station, 'volume_level')|float(0.2)}}"
  states_station: "{{states(in_station)}}"

trigger_variables:
  in_station: !input in_station

trigger:
  - platform: state
    entity_id: !input in_station
    attribute: alice_state
    to: LISTENING
  - platform: state
    entity_id: !input in_station
    attribute: alice_state
    to: SPEAKING
    id: SPEAKING

condition: 
  - condition: or
    conditions:
      - condition: not
        conditions:
          - condition: trigger
            id: SPEAKING
      - condition: and
        conditions:
          - condition: trigger
            id: SPEAKING
          - condition: template
            value_template: "{{in_speaking_condition}}"

action:
  - condition: !input in_condition
  - condition: template
    value_template: "{{old_level_voice != level_voice}}"
  - condition: template
    value_template: "{{state_attr(in_station, 'is_volume_muted') == false}}"
  - if:
      - condition: template
        value_template: "{{in_pause_play and states_station == 'playing'}}"
    then:
      - service: media_player.media_pause
        data: {}
        target:
          entity_id: !input in_station
  - service: media_player.volume_set
    target:
      entity_id: "{{in_station}}"
    data:
      volume_level: "{{level_voice}}"
  - wait_for_trigger:
      - platform: state
        entity_id: !input in_station
        attribute: alice_state
        to: IDLE
        for:
          hours: 0
          minutes: 0
          seconds: 1
    timeout: '00:10:00'
  - variables:
      volume_level: >-
        {%- if state_attr(in_station, 'volume_level')|float(0.0) !=
        level_voice -%}
          {{- (old_level_voice + state_attr(in_station, 'volume_level')|float(0.0) - level_voice)|round(1,default=20) -}}
        {%- else -%}
          {{- old_level_voice -}}
        {%- endif -%}  
  - service: media_player.volume_set
    target:
      entity_id: "{{in_station}}"
    data:
      volume_level: "{{volume_level}}"
  - if:
      - condition: template
        value_template: "{{in_pause_play and states_station == 'playing'}}"
    then:
      - service: media_player.media_play
        target:
              entity_id: !input in_station
        data: {}