blueprint:
  name: 🔮Подсветка когда говорит и слушает Алиса
  domain: automation
  description: Подсветка когда говорит и слушает Алиса
  input:
    in_station:
      name: Колонка
      description: Колонка
      selector:
        entity:
          domain: media_player
          integration: yandex_station
    in_light:
      name: Лампа
      description: Лампа для подсветки
      selector:
        entity:
            domain: light
    in_condition_activ_scene:
      name: Выключить в конце лампу
      description: Выключить в конце, не возвращать сцену до запуска.
      selector:
        entity:
    in_light_night:
      name: Признак для яркости
      description: Признак для яркости, день\ночь
      selector:
        entity:
    in_condition:
      name: (Доп) Условия для запуска
      description: Условия для запуска.
      default: []
      selector:
        action:
    in_color_speaking:
      name: Цвет когда говорит
      description: Цвет когда говорит.
      default: [190, 0 , 255]
      selector:
        color_rgb:
    in_color_listening:
      name: Цвет когда говорит
      description: Цвет когда слушает.
      default: [0, 255, 191]
      selector:
        color_rgb:

max_exceeded: silent

mode: single

variables:
  in_light: !input in_light
  in_light_night: !input in_light_night
  in_color_speaking: !input in_color_speaking
  in_color_listening: !input in_color_listening
  in_condition_activ_scene: !input in_condition_activ_scene
  scene_name: "{{'kolonka_voice_old_state_' + in_light.split('.')[1]}}"
  br_light_min: "{{(states(in_light_night) == 'off')|iif(10, 3)}}"
  br_light_max: "{{(states(in_light_night) == 'off')|iif(255, 30)}}"

trigger:
  - platform: state
    entity_id: !input in_station
    attribute: alice_state
    to: SPEAKING
  - platform: state
    entity_id: !input in_station
    attribute: alice_state
    to: LISTENING

condition: !input in_condition

action:
  - service: scene.create
    data:
      scene_id: >-
        {{scene_name}}
      snapshot_entities: !input in_light
  - repeat:
      until:
        - condition: or
          conditions: 
            - condition: state
              entity_id: !input in_station
              attribute: alice_state
              state: IDLE
              for:
                hours: 0
                minutes: 0
                seconds: 1
                milliseconds: 0
            - condition: state
              entity_id: !input in_station
              attribute: alice_state
              state: IDLE
              for:
                hours: 0
                minutes: 0
                seconds: 2
                milliseconds: 0
      sequence:
        - if:
            - condition: state
              entity_id: !input in_station
              attribute: alice_state
              state: LISTENING
          then:
                - repeat:
                    while:
                      - condition: state
                        entity_id: !input in_station
                        attribute: alice_state
                        state: LISTENING
                    sequence:

                      - variables:
                          in_color_listening: "{{in_color_listening}}"
                          brightness: "{{(states(in_light_night) == 'off')|iif(255, 30)}}"

                      - service: light.turn_on
                        data:
                          rgb_color: "{{in_color_listening}}"
                          transition: 1
                          effect: Solid
                          brightness: "{{(states(in_light_night) == 'off')|iif(255, 30)}}"
                        target:
                          entity_id: !input in_light

                      - condition: state
                        entity_id: !input in_station
                        attribute: alice_state
                        state: LISTENING

                      - wait_for_trigger:
                          - platform: state
                            entity_id: !input in_station
                            attribute: alice_state
                            # from: SPEAKING
                        timeout: '00:00:01'

                      - condition: state
                        entity_id: !input in_station
                        attribute: alice_state
                        state: LISTENING

                      - service: light.turn_on
                        data:
                          rgb_color: "{{in_color_listening}}"
                          transition: 1
                          effect: Solid
                          brightness: "{{(states(in_light_night) == 'off')|iif(10, 3)}}"
                        target:
                          entity_id: !input in_light

                      - condition: state
                        entity_id: !input in_station
                        attribute: alice_state
                        state: LISTENING

                      - wait_for_trigger:
                          - platform: state
                            entity_id: !input in_station
                            attribute: alice_state
                            # from: SPEAKING
                        timeout: '00:00:01'
          else:
                - repeat:
                    until:
                      - condition: or
                        conditions:
                          - condition: state
                            entity_id: !input in_station
                            attribute: alice_state
                            state: LISTENING
                          - condition: state
                            entity_id: !input in_station
                            attribute: alice_state
                            state: IDLE
                    sequence:

                      - variables:
                          in_color_listening: "{{in_color_listening}}"
                          brightness: "{{(states(in_light_night) == 'off')|iif(255, 30)}}"

                      - service: light.turn_on
                        data:
                          transition: 1
                          brightness: "{{(states(in_light_night) == 'off')|iif(255, 30)}}"
                          effect: Solid
                          rgb_color: "{{in_color_speaking}}"
                        target: 
                          entity_id: !input in_light

                      - condition: not
                        conditions:
                          - condition: or
                            conditions:
                              - condition: state
                                entity_id: !input in_station
                                attribute: alice_state
                                state: LISTENING
                              - condition: state
                                entity_id: !input in_station
                                attribute: alice_state
                                state: IDLE

                      - wait_for_trigger:
                          - platform: state
                            entity_id: !input in_station
                            attribute: alice_state
                            from: LISTENING
                          - platform: state
                            entity_id: !input in_station
                            attribute: alice_state
                            from: IDLE
                        timeout: '00:00:01'

                      - condition: not
                        conditions:
                          - condition: or
                            conditions:
                              - condition: state
                                entity_id: !input in_station
                                attribute: alice_state
                                state: LISTENING
                              - condition: state
                                entity_id: !input in_station
                                attribute: alice_state
                                state: IDLE

                      - service: light.turn_on
                        data:
                          brightness: "{{(states(in_light_night) == 'off')|iif(10, 3)}}"
                          transition: 1
                          effect: Solid
                          rgb_color: "{{in_color_speaking}}"
                        target: 
                          entity_id: !input in_light

                      - condition: not
                        conditions:
                          - condition: or
                            conditions:
                              - condition: state
                                entity_id: !input in_station
                                attribute: alice_state
                                state: LISTENING
                              - condition: state
                                entity_id: !input in_station
                                attribute: alice_state
                                state: IDLE

                      - wait_for_trigger:
                          - platform: state
                            entity_id: !input in_station
                            attribute: alice_state
                            from: LISTENING
                          - platform: state
                            entity_id: !input in_station
                            attribute: alice_state
                            from: IDLE
                        timeout: '00:00:01'
  - if:
      - condition: template
        value_template: "{{in_condition_activ_scene}}"
      - condition: state
        entity_id: !input in_condition_activ_scene
        state: 'on'
    then:
      - service: light.turn_off
        data: {}
        target:
          entity_id: !input in_light
    else:
      - service: scene.turn_on
        target:
          entity_id: 'scene.{{scene_name}}'