blueprint:
  name: 🔮Подсветка когда говорит и слушает Алиса
  domain: automation
  description: Подсветка когда говорит и слушает Алиса
  input:
    in_station:
      name: Колонка
      selector:
        entity:
          domain: media_player
          integration: yandex_station
    in_light:
      name: Лампы для подсветки
      selector:
        entity:
          domain: light
          multiple: true
    in_light_night:
      name: (Доп) Объект ON\OFF для уровня яркости
      description: |
        **Оставьте sun.sun если данная настройка не нужна.**
        (Доп) При состоянии ON яркость с 255\10, при OFF яркость 30\3. Например для день\ночь.
      default: sun.sun
      selector:
        entity:
    in_condition_activ_scene:
      name: (Доп) Объект ON\OFF для условия выключения лампы в конце
      description: |
        **Оставьте sun.sun если данная настройка не нужна.**
        (Доп) При состоянии ON лампа в конце будет выключена, при OFF будет возвращена сцена лампы как до запуска. 
      default: sun.sun
      selector:
        entity:
    in_condition:
      name: (Доп) Условия для запуска
      default: []
      selector:
        condition:
    in_color_speaking:
      name: (Доп) Цвет когда говорит
      default: [190, 0 , 255]
      selector:
        color_rgb:
    in_color_listening:
      name: (Доп) Цвет когда слушает
      default: [0, 255, 191]
      selector:
        color_rgb:
    in_speed_loop:
      name: (Доп) Скорость цикла и transition лампы
      default: 0.8
      selector:
        number:
          min: 0.2
          max: 1
          step: 0.1
          unit_of_measurement: s
          mode: slider

max_exceeded: silent

mode: single

variables:
  in_light: !input in_light
  in_light_night: !input in_light_night
  in_color_speaking: !input in_color_speaking
  in_color_listening: !input in_color_listening
  in_condition_activ_scene: !input in_condition_activ_scene
  scene_name: "{{this.entity_id.split('.')[1]}}"
  br_light_min: "{{(states(in_light_night) != 'on')|iif(10, 3)}}"
  br_light_max: "{{(states(in_light_night) != 'on')|iif(255, 30)}}"
  in_speed_loop: !input in_speed_loop


trigger:
  - platform: state
    entity_id: !input in_station
    attribute: alice_state
    to: SPEAKING
  - platform: state
    entity_id: !input in_station
    attribute: alice_state
    to: LISTENING

condition: !input in_condition

action:
  - service: scene.create
    data:
      scene_id: >-
        {{scene_name}}
      snapshot_entities: !input in_light
  - service: light.turn_on
    target:
      entity_id: !input in_light
  - repeat:
      until:
        - condition: or
          conditions: 
            - condition: state
              entity_id: !input in_station
              attribute: alice_state
              state: IDLE
            # - condition: state
            #   entity_id: !input in_station
            #   attribute: alice_state
            #   state: IDLE
            #   for:
            #     hours: 0
            #     minutes: 0
            #     seconds: 1
            #     milliseconds: 0
            # - condition: state
            #   entity_id: !input in_station
            #   attribute: alice_state
            #   state: IDLE
            #   for:
            #     hours: 0
            #     minutes: 0
            #     seconds: 2
            #     milliseconds: 0
            - condition: state
              entity_id: !input in_light
              state: "off"
      sequence:
        - if:
            - condition: state
              entity_id: !input in_station
              attribute: alice_state
              state: LISTENING
          then:
                - repeat:
                    while:
                      - condition: state
                        entity_id: !input in_station
                        attribute: alice_state
                        state: LISTENING
                    sequence:

                      - variables:
                          in_color_listening: "{{in_color_listening}}"
                          brightness: >-
                            {%- if states(in_light_night) != 'on' and repeat.index%2 != 0 -%}
                              255
                            {%- elif states(in_light_night) != 'on' and repeat.index%2 == 0 -%}
                              30
                            {%- elif repeat.index%2 != 0 -%}
                              10
                            {%- else -%}
                              3
                            {%- endif -%}

                      - condition: state
                        entity_id: !input in_light
                        state: "on"

                      - service: light.turn_on
                        data:
                          rgb_color: "{{in_color_listening}}"
                          transition: "{{in_speed_loop}}"
                          effect: Solid
                          brightness: "{{brightness}}"
                        target:
                          entity_id: !input in_light

                      - condition: state
                        entity_id: !input in_station
                        attribute: alice_state
                        state: LISTENING

                      - condition: state
                        entity_id: !input in_light
                        state: "on"

                      - wait_for_trigger:
                          - platform: state
                            entity_id: !input in_station
                            attribute: alice_state
                            # from: SPEAKING
                          - platform: state
                            entity_id: !input in_light
                            from: "off"
                        timeout: '00:00:0{{in_speed_loop}}'

          else:
                - repeat:
                    until:
                      - condition: or
                        conditions:
                          - condition: state
                            entity_id: !input in_station
                            attribute: alice_state
                            state: LISTENING
                          - condition: state
                            entity_id: !input in_station
                            attribute: alice_state
                            state: IDLE
                    sequence:

                      - variables:
                          in_color_listening: "{{in_color_listening}}"
                          brightness: >-
                            {%- if states(in_light_night) != 'on' and repeat.index%2 != 0 -%}
                              255
                            {%- elif states(in_light_night) != 'on' and repeat.index%2 == 0 -%}
                              30
                            {%- elif repeat.index%2 != 0 -%}
                              10
                            {%- else -%}
                              3
                            {%- endif -%}

                      - condition: state
                        entity_id: !input in_light
                        state: "on"

                      - service: light.turn_on
                        data:
                          transition: "{{in_speed_loop}}"
                          brightness: "{{brightness}}"
                          effect: Solid
                          rgb_color: "{{in_color_speaking}}"
                        target: 
                          entity_id: !input in_light

                      - condition: not
                        conditions:
                          - condition: or
                            conditions:
                              - condition: state
                                entity_id: !input in_station
                                attribute: alice_state
                                state: LISTENING
                              - condition: state
                                entity_id: !input in_station
                                attribute: alice_state
                                state: IDLE

                      - condition: state
                        entity_id: !input in_light
                        state: "on"

                      - wait_for_trigger:
                          - platform: state
                            entity_id: !input in_station
                            attribute: alice_state
                            from: LISTENING
                          - platform: state
                            entity_id: !input in_station
                            attribute: alice_state
                            from: IDLE
                          - platform: state
                            entity_id: !input in_light
                            from: "off"
                        timeout: '00:00:0{{in_speed_loop}}'

  - condition: state
    entity_id: !input in_light
    state: "on"

  - if:
      - condition: template
        value_template: "{{in_condition_activ_scene != 'sun.sun'}}"
      - condition: state
        entity_id: !input in_condition_activ_scene
        state: 'on'
    then:
      - service: light.turn_off
        data: {}
        target:
          entity_id: !input in_light
    else:
      - service: scene.turn_on
        target:
          entity_id: 'scene.{{scene_name}}'
