blueprint:
  name: 📦Подсветка когда говорит и слушает Алиса
  domain: automation
  description: Подсветка когда говорит и слушает Алиса
  input:
    alisa_state:
      name: Состояние колонки
      description: Состояние колонки
      selector:
        entity:
          domain: sensor
    light_v:
      name: Лампа
      description: Лампа для подсветки
      selector:
        entity:
            domain: light
            # integration: wled
    entity_end_off:
      name: Признак
      description: Выключить в конце лампу или не запускать авто, если включен  ->
      selector:
        entity:
    # entity_lux:
    #   name: Признак
    #   description: На максимум или минимум включать подсветку  ->
    #   selector:
    #     entity:
    no_trigger1:
      name: Исключить скрипт или автоматизацию
      description: Исключить скрипт или автоматизацию
      selector:
        entity:
    no_trigger2:
      name: Исключить скрипт или автоматизацию
      description: Исключить скрипт или автоматизацию
      selector:
        entity:
    no_trigger3:
      name: Исключить скрипт или автоматизацию
      description: Исключить скрипт или автоматизацию
      selector:
        entity:
    no_trigger4:
      name: Исключить скрипт или автоматизацию
      description: Исключить скрипт или автоматизацию
      selector:
        entity:
    no_trigger5:
      name: Исключить скрипт или автоматизацию
      description: Исключить скрипт или автоматизацию
      selector:
        entity:
    no_trigger6:
      name: Исключить скрипт или автоматизацию
      description: Исключить скрипт или автоматизацию
      selector:
        entity:
    no_trigger7:
      name: Исключить скрипт или автоматизацию
      description: Исключить скрипт или автоматизацию
      selector:
        entity:
    no_trigger8:
      name: Исключить скрипт или автоматизацию
      description: Исключить скрипт или автоматизацию
      selector:
        entity:
    # no_trigger10:
    #   name: Исключить скрипт или автоматизацию
    #   description: Исключить скрипт или автоматизацию
    #   default: "{{ as_timestamp(now())-as_timestamp(state_attr('automation.*******','last_triggered'))|float > 30 }}"
    #   selector:
    #     object:
max_exceeded: silent

variables:
  light_v_p: !input light_v
  scene_name: "{{'kolonka_voice_old_state_'+light_v_p.split('.')[1]}}"
  scene_name_domain: "{{'scene.kolonka_voice_old_state_'+light_v_p.split('.')[1]}}"
  br_light_min: >-
    {% if states('input_boolean.priznak_dlia_vechera') == "off"%}
      10
    {%else%}
      3
    {%endif%}
  br_light_max: >-
    {% if states('input_boolean.priznak_dlia_vechera') == "off"%}
      255
    {%else%}
      30
    {%endif%}

#   default_time_on2: "2333"
#   default_time_on3: "{{default_time_on|split('-')}}"

trigger:
  - platform: state
    entity_id: !input alisa_state
    to: LISTENING
  - platform: state
    entity_id: !input alisa_state
    to: SPEAKING
condition:
  - condition: and
    conditions:
      - condition: numeric_state
        entity_id: !input no_trigger1
        below: '1'
        attribute: current
      - condition: numeric_state
        entity_id: !input no_trigger2
        below: '1'
        attribute: current
      - condition: numeric_state
        entity_id: !input no_trigger3
        below: '1'
        attribute: current
      - condition: numeric_state
        entity_id: !input no_trigger4
        below: '1'
        attribute: current
      - condition: numeric_state
        entity_id: !input no_trigger5
        below: '1'
        attribute: current
      - condition: numeric_state
        entity_id: !input no_trigger6
        below: '1'
        attribute: current
      - condition: numeric_state
        entity_id: !input no_trigger7
        below: '1'
        attribute: current
      - condition: numeric_state
        entity_id: !input no_trigger8
        below: '1'
        attribute: current
      - condition: state
        entity_id: !input entity_end_off
        state: 'off'
      # - condition: template
      #   value_template: !input no_trigger10
action:

  - condition: and
    conditions:
      - condition: numeric_state
        entity_id: !input no_trigger1
        below: '1'
        attribute: current
      - condition: numeric_state
        entity_id: !input no_trigger2
        below: '1'
        attribute: current
      - condition: numeric_state
        entity_id: !input no_trigger3
        below: '1'
        attribute: current
      - condition: numeric_state
        entity_id: !input no_trigger4
        below: '1'
        attribute: current
      - condition: numeric_state
        entity_id: !input no_trigger5
        below: '1'
        attribute: current
      - condition: numeric_state
        entity_id: !input no_trigger6
        below: '1'
        attribute: current
      - condition: numeric_state
        entity_id: !input no_trigger7
        below: '1'
        attribute: current
      - condition: numeric_state
        entity_id: !input no_trigger8
        below: '1'
        attribute: current
      - condition: state
        entity_id: !input entity_end_off
        state: 'off'




  - service: scene.create
    data:
      scene_id: >-
        {{scene_name}}
      snapshot_entities: !input light_v
  - repeat:
      until:
        - condition: or
          conditions: 
            - condition: state
              entity_id: !input alisa_state
              state: IDLE
              for:
                hours: 0
                minutes: 0
                seconds: 1
                milliseconds: 0
            - condition: state
              entity_id: !input alisa_state
              state: IDLE
              for:
                hours: 0
                minutes: 0
                seconds: 2
                milliseconds: 0
      sequence:
        - choose:
            - conditions:
                - condition: state
                  entity_id: !input alisa_state
                  state: LISTENING
              sequence:
                - repeat:
                    while:
                      - condition: state
                        entity_id: !input alisa_state
                        state: LISTENING
                    sequence:

                      - service: light.turn_on
                        data:
                          rgb_color:
                            - 0
                            - 255
                            - 191
                          transition: 1
                          effect: Solid
                          brightness: >-
                            {{br_light_max}}
                        target:
                          entity_id: !input light_v

                      - condition: state
                        entity_id: !input alisa_state
                        state: LISTENING

                      - wait_for_trigger:
                          - platform: state
                            entity_id: !input alisa_state
                            # from: SPEAKING
                        timeout: '00:00:01'

                      - condition: state
                        entity_id: !input alisa_state
                        state: LISTENING

                      - service: light.turn_on
                        data:
                          rgb_color:
                            - 0
                            - 255
                            - 191
                          transition: 1
                          effect: Solid
                          brightness: >-
                            {{br_light_min}}
                        target:
                          entity_id: !input light_v

                      - condition: state
                        entity_id: !input alisa_state
                        state: LISTENING

                      - wait_for_trigger:
                          - platform: state
                            entity_id: !input alisa_state
                            # from: SPEAKING
                        timeout: '00:00:01'
          default:
                - repeat:
                    until:
                      - condition: or
                        conditions:
                          - condition: state
                            entity_id: !input alisa_state
                            state: LISTENING
                          - condition: state
                            entity_id: !input alisa_state
                            state: IDLE
                    sequence:
                      - service: light.turn_on
                        data:
                          transition: 1
                          brightness: >-
                            {{br_light_max}}
                          effect: Solid
                          rgb_color:
                            - 190
                            - 0
                            - 255
                        target: 
                          entity_id: !input light_v

                      - condition: not
                        conditions:
                          - condition: or
                            conditions:
                              - condition: state
                                entity_id: !input alisa_state
                                state: LISTENING
                              - condition: state
                                entity_id: !input alisa_state
                                state: IDLE

                      - wait_for_trigger:
                          - platform: state
                            entity_id: !input alisa_state
                            from: LISTENING
                          - platform: state
                            entity_id: !input alisa_state
                            from: IDLE
                        timeout: '00:00:01'

                      - condition: not
                        conditions:
                          - condition: or
                            conditions:
                              - condition: state
                                entity_id: !input alisa_state
                                state: LISTENING
                              - condition: state
                                entity_id: !input alisa_state
                                state: IDLE

                      - service: light.turn_on
                        data:
                          brightness: >-
                            {{br_light_min}}
                          transition: 1
                          effect: Solid
                          rgb_color:
                            - 190
                            - 0
                            - 255
                        target: 
                          entity_id: !input light_v

                      - condition: not
                        conditions:
                          - condition: or
                            conditions:
                              - condition: state
                                entity_id: !input alisa_state
                                state: LISTENING
                              - condition: state
                                entity_id: !input alisa_state
                                state: IDLE

                      - wait_for_trigger:
                          - platform: state
                            entity_id: !input alisa_state
                            from: LISTENING
                          - platform: state
                            entity_id: !input alisa_state
                            from: IDLE
                        timeout: '00:00:01'
  # - service: scene.turn_on
  #   target:
  #     entity_id: >-
  #       {{scene_name_domain}}
  - if:
      - condition: state
        entity_id: !input entity_end_off
        state: 'off'
    then:
      - service: scene.turn_on
        target:
          entity_id: '{{scene_name_domain}}'
    else:
      - service: light.turn_off
        data: {}
        target:
          entity_id: !input light_v


mode: single
