blueprint:
  name: Действия при изменении состояния обекта
  domain: automation
  input:
    in_entity:
      name: Обект для отслеживания
      description: Обект для отслеживания
      selector:
        entity:
    turn_on_reload_auto:
      name: Запускать при рестарте автоматизаций
      default: true
      selector:
        boolean:
    turn_on_start_ha:
      name: Запускать при рестарте homeassistant
      default: true
      selector:
        boolean:
    state_off_action:
      name: Учитывать состояние OFF
      description: Необходимо заполнить действие при OFF
      default: false
      selector:
        boolean:
    in_action_on:
      name: Дейтсвия при ON
      description: Дейтсвия при ON
      default: []
      selector:
        action:
    in_action_off:
      name: Дейтсвия при OFF
      description: Дейтсвия при OFF
      default: []
      selector:
        action:
    in_action_default:
      name: Дейтсвия DEFAULT
      description: Дейтсвия DEFAULT
      default: []
      selector:
        action:
#max_exceeded: silent

variables:
  turn_on_reload_auto: !input turn_on_reload_auto
  turn_on_start_ha: !input turn_on_start_ha
  state_off_action: !input state_off_action

trigger:
  - platform: state
    entity_id: !input in_entity
    id: e_state
    to: ~
  - platform: homeassistant
    event: start
    id: e_start
  - platform: event
    event_type: automation_reloaded
    id: e_reload
condition: 
  - condition: or
    conditions:
      - condition: trigger
        id: e_state
      - condition: and
        conditions:
          - condition: trigger
            id: e_start
          - condition: template
            value_template: "{{turn_on_start_ha}}"
      - condition: and
        conditions:
          - condition: trigger
            id: e_reload
          - condition: template
            value_template: "{{turn_on_reload_auto}}"
action: 
  - choose:
      - conditions:
          - condition: state
            entity_id: !input in_entity
            state: 'on'
        sequence: !input in_action_on
      - conditions:
          - condition: and
            conditions:
              - condition: state
                entity_id: !input in_entity
                state: 'off'
              - condition: template
                value_template: "{{state_off_action}}"
        sequence: !input in_action_off
    default: !input in_action_default
mode: restart