blueprint:
  name: Действия при команде Алисе
  description: Действия при команде Алисе
  domain: automation
  input:
    in_text:
      name: Команда
      description: Команда
      selector:
        text:
    in_action:
      name: Дейтсвия
      description: Дейтсвия
      default: []
      selector:
        action:
#max_exceeded: silent

trigger:
  - platform: event
    event_type: yandex_intent
    event_data:
      text: !input in_text
condition: []
action:
  - choose:
      - conditions: []
        sequence: !input in_action
mode: restart