blueprint:
  name: Громкость колонки когда говорит и слушает
  domain: automation
  description: Громкость колонки когда говорит и слушает
  input:
    alisa_state:
      name: Алиса
      description: Алиса
      selector:
        entity:
          domain: sensor
    kolonka:
      name: Колонка
      description: Колонка
      selector:
        entity:
          domain: media_player
          integration: yandex_station
    level_voice_entity:
      name: Объект для громкости
      description: Объект для громкости
      selector:
        entity:
          domain: input_number
    level_voice:
      name: Громкость когда говорит
      description: Громкость когда говорит
      selector:
        number:
          min: 0
          max: 100
          step: 10
    no_trigger1:
      name: Исключить скрипт или автоматизацию
      description: Исключить скрипт или автоматизацию
      selector:
        entity:
    no_trigger2:
      name: Исключить скрипт или автоматизацию
      description: Исключить скрипт или автоматизацию
      selector:
        entity:
    no_trigger3:
      name: Исключить скрипт или автоматизацию
      description: Исключить скрипт или автоматизацию
      selector:
        entity:
    no_trigger4:
      name: Исключить скрипт или автоматизацию
      description: Исключить скрипт или автоматизацию
      selector:
        entity:
    no_trigger5:
      name: Исключить Объект
      description: Исключить Объект
      selector:
        entity:

max_exceeded: silent

variables:
  level_voice_n: !input level_voice
  kolonka: !input kolonka
  level_voice: "{{level_voice_n / 100}}"
  old_level_voice: >-
    {%if state_attr(kolonka, 'volume_level')|float(0) * 100 >= states('input_number.gromkost_kolonki_kogda_govorit')|float(0) %}
    {{states('input_number.minimalnaia_gromkost_kolonki')|float(0) / 100}}
    {%else%}
    {{state_attr(kolonka, 'volume_level')}}
    {%endif%}

trigger:
  - platform: state
    entity_id: !input kolonka
    attribute: alice_state
    to: LISTENING
  - platform: state
    entity_id: !input kolonka
    attribute: alice_state
    to: SPEAKING
condition: 
  - condition: and
    conditions:
      - condition: numeric_state
        entity_id: !input no_trigger1
        below: '1'
        attribute: current
      - condition: numeric_state
        entity_id: !input no_trigger2
        below: '1'
        attribute: current
      - condition: numeric_state
        entity_id: !input no_trigger3
        below: '1'
        attribute: current
      - condition: numeric_state
        entity_id: !input no_trigger4
        below: '1'
        attribute: current
      - condition: not
        conditions:
          - condition: state
            entity_id: !input no_trigger5
            state: 'on'

action:
  - condition: not
    conditions:
      - condition: state
        entity_id: !input alisa_state
        state: IDLE
  - service: media_player.volume_set
    target:
      entity_id: !input kolonka
    data:
      volume_level: "{{level_voice }}"
  - wait_for_trigger:
      - platform: state
        entity_id: !input alisa_state
        to: IDLE
        for:
          hours: 0
          minutes: 0
          seconds: 1
          milliseconds: 0
      - platform: state
        entity_id: !input alisa_state
        to: IDLE
        for:
          hours: 0
          minutes: 0
          seconds: 2
          milliseconds: 0
      - platform: state
        entity_id: !input alisa_state
        to: IDLE
        for:
          hours: 0
          minutes: 0
          seconds: 3
          milliseconds: 0
    timeout: '00:10:00'
  - service: media_player.volume_set
    target:
      entity_id: !input kolonka
    data:
      volume_level: >-
        {{ old_level_voice + (state_attr(kolonka, 'volume_level') - level_voice)|round(1,default=20) }}
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 0
mode: queued
max: 4