blueprint:
  name: Не выключать устройство
  description: Не выключать устройство
  domain: automation
  input:
    entity_id_in:
      name: Объект
      description: Объект
      selector:
        entity: 
    scheduled_action:
      name: Дополнительное действия
      description: Дополнительное действия
      default: []
      selector:
        action:

trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: state
    entity_id: !input entity_id_in
    to: ~
condition: []
action:
  - service: homeassistant.turn_on
    target: 
      entity_id: !input entity_id_in
  - choose:
      - conditions: []
        sequence: !input scheduled_action
mode: single
max_exceeded: silent