blueprint:
  name: Включение и выключение по времени и дню недели
  description: Включение по времени и дню недели
  domain: automation
  input:
    entity_id_in:
      name: Объекты
      description: Объекты
      selector:
        target: 
    default_time_on:
      name: Время включения
      description: Время включения
      default: '12:00:00'
      selector:
        time:
    default_time_off:
      name: Время выключения
      description: Время выключения
      default: '00:00:00'
      selector:
        time:
    monday_enabled:
      name: Понедельник
      default: true
      selector:
        boolean:
    tuesday_enabled:
      name: Вторник
      default: true
      selector:
        boolean:
    wednesday_enabled:
      name: Среда
      default: true
      selector:
        boolean:
    thursday_enabled:
      name: Четверг
      default: true
      selector:
        boolean:
    friday_enabled:
      name: Пятница
      default: true
      selector:
        boolean:
    saturday_enabled:
      name: Суббота
      default: true
      selector:
        boolean:
    sunday_enabled:
      name: Воскресенье
      default: true
      selector:
        boolean:
    scheduled_action:
      name: Дополнительное действия
      description: Дополнительное действия
      default: []
      selector:
        action:

variables:
  monday_enabled: !input monday_enabled
  tuesday_enabled: !input tuesday_enabled
  wednesday_enabled: !input wednesday_enabled
  thursday_enabled: !input thursday_enabled
  friday_enabled: !input friday_enabled
  saturday_enabled: !input saturday_enabled
  sunday_enabled: !input sunday_enabled
  current_day: "{{ now().weekday() | int }}"

trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: time
    at: !input default_time_on
  - platform: time
    at: !input default_time_off
condition:
  - condition: template
    value_template: >-
        {{ 
          (current_day == 0 and monday_enabled) or 
          (current_day == 1 and tuesday_enabled) or 
          (current_day == 2 and wednesday_enabled) or
          (current_day == 3 and thursday_enabled) or 
          (current_day == 4 and friday_enabled) or
          (current_day == 5 and saturday_enabled) or
          (current_day == 6 and sunday_enabled)
        }}
action:
  - choose:
      - conditions:
          - condition: time
            after: !input default_time_on
            before: !input default_time_off
        sequence:
          - service: homeassistant.turn_on
            target: !input entity_id_in
    default:
      - service: homeassistant.turn_off
        target: !input entity_id_in
  - choose:
      - conditions: []
        sequence: !input scheduled_action
mode: single
max_exceeded: silent