blueprint:
  name: Пауза и плей когда говорит или слушает колонка Алиса
  domain: automation
  description: Пауза и плей когда говорит или слушает колонка Алиса
  input:
    kolonka:
      name: Колонка
      description: Колонка
      selector:
        entity:
          domain: media_player
          integration: yandex_station
    dop_entity:
      name: Доп объект
      description: Дополнительный объект для паузы и возврата
      selector:
        entity:
    no_trigger1:
      name: Объект для исключения
      description: Не возвращать если ВКЛючен объект
      selector:
        entity:

max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input kolonka
    attribute: alice_state
    to: LISTENING
  - platform: state
    entity_id: !input kolonka
    attribute: alice_state
    to: SPEAKING
  - platform: state
    entity_id: !input dop_entity
    from: 'off'
    to: 'on'

condition: 
  - condition: state
    entity_id: !input kolonka
    state: playing
action:
  - service: media_player.media_pause
    data: {}
    target:
      entity_id: !input kolonka
  - choose:
      - conditions:
          - condition: or
            conditions:
              - condition: not
                conditions:
                  - condition: state
                    entity_id: !input kolonka
                    state: IDLE
                    attribute: alice_state
              - condition: state
                entity_id: !input dop_entity
                state: 'on'
        sequence:
          - wait_for_trigger:
              - platform: state
                attribute: alice_state
                to: IDLE
                entity_id: !input kolonka
                for:
                  hours: 0
                  minutes: 0
                  seconds: 1
              - platform: state
                to: 'off'
                entity_id: !input dop_entity
            continue_on_timeout: true
            timeout: '00:10:00'
    default: []
  - condition: template
    value_template: '{{ wait.remaining > 1 }}'
  - condition: state
    entity_id: !input no_trigger1
    state: 'off'
  - service: media_player.media_play
    target:
      entity_id: !input kolonka
    data: {}
mode: parallel
max: 10
